#define UWORLD 0x170D9D88 //UWORLD/GWORLD
#define GAME_INSTANCE 0x200 //GAMEINSTANCE
#define LOCAL_PLAYERS 0x38 //LOCALPLAYERS
#define PLAYER_CONTROLLER 0x30 //PLAYERCONTROLLER
#define LOCAL_PAWN 0x350 //LOCALPAWN //AACTOR
#define PAWN_PRIVATE 0x320 //PAWNPRIVATE /ACCTOR I THINK
#define ROOT_COMPONENT 0x1B0 //ROOTC /ROOTCOMPONENT //0x1B0
#define RELATIVE_LOCATION 0x120 //RELATIVELOCATION //0x120
#define PLAYER_STATE 0x2C8 //PLAYERSTATE //DONTREMEBER WHERE IT IS IN SDK //0x2B0
#define TEAM_INDEX 0x1261 //DONTREMEBER WHERE IT IS IN SDK //0x1239
#define GAME_STATE 0x188 //UPD
#define PLAYER_ARRAY 0x2C0 //PLAYERARRAY
#define MESH 0x328 //UPD
#define COMPONENT_TO_WORLD 0x1E0 //230
#define BONE_ARRAY 0x5A8 //UPD
#define BONE_ARRAY_CACHE 0x5B8 //DONTREMEBER WHERE IT IS IN SDK
#define LAST_SUBMIT_TIME 0x2E8 //DONTREMEBER WHERE IT IS IN SDK //0x2EC //0x2E0  //0x2E8
#define LAST_SUBMIT_TIME_ON_SCREEN 0x2F0 //DONTREMEBER WHERE IT IS IN SDK //0X2E8
#define VELOCITY 0x168 //UPD

ALL OFFSETS UPDATED ENJOY!
